InternalOAuthError: pluppppp

    at OAuth2Strategy._createOAuthError (/app/node_modules/passport-oauth2/lib/strategy.js:426:17)

    at /app/node_modules/passport-oauth2/lib/strategy.js:179:36

    at /app/node_modules/oauth/lib/oauth2.js:191:18

    at ClientRequest.<anonymous> (/app/node_modules/oauth/lib/oauth2.js:162:5)

    at ClientRequest.emit (node:events:390:28)

    at Socket.socketErrorListener (node:_http_client:447:9)

    at Socket.emit (node:events:390:28)

    at emitErrorNT (node:internal/streams/destroy:164:8)

    at emitErrorCloseNT (node:internal/streams/destroy:129:3)

    at processTicksAndRejections (node:internal/process/task_queues:83:21)

plupp1:  Error: connect ECONNREFUSED 127.0.0.1:8081

    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {

  errno: -111,

  code: 'ECONNREFUSED',

  syscall: 'connect',

  address: '127.0.0.1',

  port: 8081

}

InternalOAuthError: pluppppp

    at OAuth2Strategy._createOAuthError (/app/node_modules/passport-oauth2/lib/strategy.js:426:17)

    at /app/node_modules/passport-oauth2/lib/strategy.js:179:36

    at /app/node_modules/oauth/lib/oauth2.js:191:18

    at ClientRequest.<anonymous> (/app/node_modules/oauth/lib/oauth2.js:162:5)

    at ClientRequest.emit (node:events:390:28)

    at Socket.socketErrorListener (node:_http_client:447:9)

    at Socket.emit (node:events:390:28)

    at emitErrorNT (node:internal/streams/destroy:164:8)

    at emitErrorCloseNT (node:internal/streams/destroy:129:3)

    at processTicksAndRejections (node:internal/process/task_queues:83:21)